### PR TITLE
Support carthage and cocoapods

### PR DESCRIPTION
**Pull request by iida-hayato**
- [x] separate Rx and  Reactive modules
- [x] add Cartfile
- [x] test`pod install` (in Example dir)
- [x] test `carthage update` (in [here](https://github.com/iida-hayato/RxMoyaSwiftyJSONMapper-Sample))

### CODE REVIEW

**Comment by AvdLee** [comment]
Looks good! What's the reason for renaming?

**Comment by iida-hayato** [comment]
@AvdLee 
thanks!

> What's the reason for renaming?

you mean this commit? [https://github.com/AvdLee/Moya-SwiftyJSONMapper/pull/7/commits/e41523ddc453e69baabc4e3aab699524ec1cd4da]

Because Carthage can't build repository  contains `-`  like `Moya-SwiftyJSONMapper`.
So I  remove '-'.

**Comment by AvdLee** [comment]
ah, fair enough :) Thanks for the contribution!

**Comment by AvdLee** [comment]
I've reverted this change. It removed the workspace and the included tests which I used. You can add Carthage support again if you want, but make sure the workspace stays and the unit tests inside still work as they do now

**Pull request merged**
