### PR TITLE
Upgrade to Moya v10 and Swift 4

### PR DESCRIPTION
**Pull request by akshay23**
Initially upgraded to Moya v9 to address the breaking changes, then upgraded to Moya 10 which did not have any changes that affected this library.

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]
Looks good, well done. After CI succeeds, we can merge it in.

**Comment by AvdLee** [comment]
@akshay23 are you able to upgrade CI as well? Should be as easy as adding xcode9.1 to travis.yml

**Comment by akshay23** [comment]
Thanks for the quick review @AvdLee. Just changed the travis.yml file.

**Comment by akshay23** [comment]
@AvdLee CI failed due to some weird issue with travis. Any idea how to fix it? I haven't travis a lot so not sure how to proceed

**Comment by AvdLee** [comment]
@akshay23 it seems to be working, great job!

**Pull request merged**
